# Generated by Django 5.0.1 on 2024-01-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=250)),
                ('website_link', models.URLField()),
                ('website_password', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
